De app dependency zoekt naar een jar file welke niet bestaat. Ik heb hem nu gegenereerd. Daarnaast kreeg ik errors over de SDK Build Tools versie, die moest 27.0.3 zijn. En de gradle build versies zijn bij mij geupdate naar 4.4 "compile" vervangen worden met "implementation"
Ik krijg alleen nu zelf een error als ik de app draai, op een of andere manier ben ik null pakketten aan het versturen maar ik snap niet waarom:

04-04 09:11:30.349 5479-5523/com.app.feut.feut E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.app.feut.feut, PID: 5479
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.feut.shared.connection.Client.sendPacket(com.feut.shared.connection.packets.Packet)' on a null object reference
        at com.app.feut.feut.connection.SendPacketTask.doInBackground(SendPacketTask.java:18)
        at com.app.feut.feut.connection.SendPacketTask.doInBackground(SendPacketTask.java:11)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
04-04 09:11:30.534 5479-5517/com.app.feut.feut E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe966c280